Repository pagopa/pagopa-print-payment-notice-generator, pull requests merged in 2024-06, with the labels that each got.

#9 fix: model and mapper
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImpl.java
Labels: enhancement, patch

#8 helm values
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notice/generator/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/NoticeRequestData.java
  src/main/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImpl.java
  src/main/resources/application-local.properties.encrypted
  src/main/resources/application.properties
Labels: patch

#11 fix: Update NoticeGenerationServiceImpl
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
Labels: enhancement, size/small, patch

#12 fix: Update TemplateDataMapper
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
Labels: size/small, patch

#13 [VAS-1086] feat: updated mapper
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImpl.java
Labels: bug, size/small, patch

#14 fix helm
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/resources/logback-spring.xml
Labels: size/small, patch

#15 [VAS-1101] feat: add dynamic validation for template models
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/notice/generator/exception/AppError.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/TemplateResource.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notice/generator/storage/NoticeTemplateStorageClient.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImplTest.java
  src/test/java/it/gov/pagopa/payment/notice/generator/storage/NoticeTemplateStorageClientTest.java
  src/test/resources/application.properties
Labels: enhancement, minor

#17 [VAS-1147] fix: cds model
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/pdf/notice/InstallmentDiscounted.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/pdf/notice/InstallmentReduced.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/pdf/notice/Installments.java
  src/main/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImpl.java
  src/test/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImplTest.java
Labels: bug, size/small, patch
