Repository pagopa/pagopa-print-payment-notice-generator, pull requests merged in 2024-05, with the labels that each got.

#2 .identity
  .identity/00_data.tf
  .identity/01_github_environment.tf
  .identity/02_application_action.tf
  .identity/99_variables.tf
Labels: size/small, skip

#5 fix: missing data for poste template added
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
Labels: bug, size/small, patch

#6 [VAS-835] feat: add complete management event
  .gitignore
  Dockerfile
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/notice/generator/client/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/payment/notice/generator/events/consumer/NoticeGenerationConsumerConfig.java
  src/main/java/it/gov/pagopa/payment/notice/generator/events/producer/NoticeRequestCompleteProducer.java
  src/main/java/it/gov/pagopa/payment/notice/generator/events/producer/NoticeRequestCompleteProducerImpl.java
  src/main/java/it/gov/pagopa/payment/notice/generator/mapper/TemplateDataMapper.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/enums/PaymentGenerationRequestStatus.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/CreditorInstitution.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/InstallmentData.java
  src/main/java/it/gov/pagopa/payment/notice/generator/model/notice/Notice.java
  src/main/java/it/gov/pagopa/payment/notice/generator/repository/PaymentGenerationRequestRepository.java
  src/main/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImpl.java
  src/main/java/it/gov/pagopa/payment/notice/generator/util/CommonUtility.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/notice/generator/events/producer/NoticeRequestCompleteProducerImplTest.java
  src/test/java/it/gov/pagopa/payment/notice/generator/service/NoticeGenerationServiceImplTest.java
Labels: enhancement, minor, size/large
